### ISSUE TITLE
Calculate NDVI on multiple observation areas per picture

### ISSUE THREAD

**Issue by united-ecology** [united-ecology/photomoss#1]
At the moment only one polygon per picture can be defined/drawn to calculate NDVI.
But our pictures contain several individual pots in which NDVI needs to be calculated.

Two approaches appear feasible:
1. iterate through a multiple-polygon layer for each picture
2. iterate through pictures using single-polygon layers

**Comment by indradecastro** [comment]
@scolymushisp I have [uploaded right now](https://github.com/united-ecology/photomoss/commit/90a450fcf7225b47f5f5a90f61cd89769d549478) functions that:

> iterate through a multiple-polygon layer for each picture
